name: ags-tool
base: core18
version: '0.1'
summary: A tool for the AG Geiler Scheiss
description: |
  https://github.com/mkg20001/ags-tool WIP

architectures:
  - build-on: amd64

grade: stable
confinement: strict

apps:
  ags-tool:
    command: ags-tool
    plugs: [network, network-bind]
    daemon: simple

parts:
  ags-tool:
    plugin: nodejs
    nodejs-version: 10.16.3
    override-install: |
      npm prune
      snapcraftctl install
    source: .
    build-packages:
      - git
      - python2.7
